apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-cartservice
  namespace: boutique
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: cartservice
