apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-frontend
  namespace: boutique
spec:
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: frontend
  stressors:
    cpu:
      workers: 2
      load: 85
  duration: "5m"
