kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: chaos-lab
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 31000
        hostPort: 3000
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 32333
        hostPort: 2333
        listenAddress: "127.0.0.1"
        protocol: TCP
